
framework:
    secret: '%env(APP_SECRET)%'
    
    # Configuration session sécurisée 
    session:
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: strict
        name: ATLAS_SESSID
        gc_maxlifetime: 604800
        
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file